_target_: pytorch_lightning.Trainer

devices: 'auto' # also numbers
accelerator: 'auto' #cpu, tpu, (devices=4, accelerator="gpu", strategy="ddp"), (devices="auto", accelerator="auto")

accumulate_grad_batches: 1
max_epochs: 1000 #(-1) for infinite
min_epochs: 10
max_steps: -1
check_val_every_n_epoch: 1
#val_check_interval: ${mult_int:${.accumulate_grad_batches}, 1000}
log_every_n_steps: 1

fast_dev_run: False # True, False, or int (7) (limit_train_batches=1.0, or 10)
# overfit_batches: 0.01
# reload_dataloaders_every_n_epochs: 0

