_target_: src.models.collators.tokenizers.simple_word_level_tokenizer.SimpleWordLevelTokenizer

model_max_length: ${model.collator.max_length}
vocab_size: 30

batch_size: ${datamodule.dataset_parameters.batch_size}
tokenize_prior_training: True