_target_: src.models.modules.discrete_layers.softmax.SoftmaxContinousLayer
key: softmax_continous
temperature: 1.0
dictionary_dim: 256

bottleneck_normalization_args:
  type: batch norm # batch norm, layer norm, weight norm or null
  #args: #specify dictionar of args here for layer norm or weight norm
  #args for batch norm
  args:
    eps: 1e-5
    momentum: 0.1
    affine: true
  #args for layer norm
  # args:
  #   eps: 1e-5
  #   elementwise_affine: true