_target_: src.models.from_blocks_library.XZAutoencoder
name: "XZAutoencoderFromBlocks"

defaults:
  # - inference: default
  - blocks_model: pretrained_t5 # untrained_bart, pretrained_t5
  - collator: simple_text_collator
  - lr_scheduler: reduce_on_plateau # options: 
  - optimizer: default # options: default (Adam), AdamW

special_tokens: ${model.blocks_model.hydra_configs.special_tokens}
discretizer_key: "softmax"

model_params:
  use_pc_grad: False

  # for gradient inner product logging in val step 
  log_gradient_stats: False
  num_steps_log_gradient_stats: 8
  log_gradient_stats_batch_size: 32

  acc_grad_batch: 1
  num_bootstrap_tests: 10

  max_x_length: 100
  max_x_vocab_size: 200
  max_z_length: 100
  max_z_vocab_size: 200
  decode_after_autoreg_step: True

  usexz: True
  usex: True
  usez: True
  
  loss_coeff:
    xzx: 1.0
    zxz: 1.0
    supervised_seperated_x: 1.0
    supervised_seperated_z: 1.0
    quantization_supervised_seperated: 1.0
    quantization_zxz: 1.0
    quantization_xzx: 1.0
  
  use_tokenizer_vocab_len: true
  disc_x_vocab_size: -1
  disc_z_vocab_size: -1
  