_target_: src.models.xz_autoencoder.XZAutoencoder.load_from_checkpoint

checkpoint_path: ???

substitute_config:
  model_params:
    loss_coeff:
      # turn them to -1 to disable that loss, (in training, not in validation)
      xzx: 1.0
      zxz: 1.0
      supervised_seperated_x: 1.0
      supervised_seperated_z: 1.0
  
    acc_grad_batch: 16

  optimizer:
    lr: 0.002

  lr_scheduler:
    mode: "min"
    factor: 0.8
    patience: 5
    threshold: 0.01
    threshold_mode: "abs"
    cooldown: 5
    min_lr: 1e-6
    eps: 1e-8
    verbose: True

