_target_: src.models.xz_autoencoder.XZAutoencoder
name: "XZAutoencoder"

defaults:
  # - inference: default
  - discretizer: gumbel
  - collator: simple_text_collator
  - lr_scheduler: reduce_on_plateau # options: 
  - optimizer: default # options: default (Adam), AdamW
  - sequence_to_sequence_model: gpt2_gpt2

special_tokens: ["[pad]", "[bos]", "[eos]", "[unk]"]

modules:
  model_x_to_z: ${model.sequence_to_sequence_model}
  model_z_to_x: ${model.sequence_to_sequence_model}
  disc_x: ${model.discretizer}
  disc_z: ${model.discretizer}

model_params:
  max_x_length: 100
  max_x_vocab_size: 200
  max_z_length: 100
  max_z_vocab_size: 200
  decode_after_autoreg_step: True
  tokenize_prior_training: True

  loss_coeff:
    xzx: 1.0
    zxz: 1.0
    supervised_seperated_x: 1.0
    supervised_seperated_z: 1.0
  
  acc_grad_batch: 1
  num_bootstrap_tests: 10
  use_tokenizer_vocab_len: true
  disc_x_vocab_size: -1
  disc_z_vocab_size: -1