defaults:
  - inference: default
  - collator: simple_text_collator
  - scheduler_config: reduce_on_plateau # options: default (ReduceLROnPlateau), linear, polynomial
  - optimizer: default # options: default (Adam), AdamW


_target_: src.models.XZAutoencoder.XZAutoencoder
name: "XZAutoencoder"

special_tokens: ["[pad]", "[bos]", "[eos]", "[unk]"]



modules:

  model_x_to_z: sequence_to_sequence_model.

  model_z_to_x: sequence_to_sequence_model.

  disc_x: discretizer.

  disc_z: discretizer.

  tokenizer_x: tokenizer.

  tokenizer_z: tokenizer.

model_params:
  reconstruction_loss_coeff_x: 1.0
  reconstruction_loss_coeff_z: 1.0

  use_tokenizer_vocab_len: true
  disc_x_vocab_size: -1
  disc_z_vocab_size: -1