_target_: src.models.xz_autoencoder.XZAutoencoder
name: "XZAutoencoder"

defaults:
  # - inference: default
  - discretizer:
    - entmax
    - gumbel
  - collator: simple_text_collator
  - lr_scheduler: reduce_on_plateau # options: 
  - optimizer: default # options: default (Adam), AdamW
  - sequence_to_sequence_model:
    - bert_bert
    - bert_gpt2

special_tokens: ["[pad]", "[bos]", "[eos]", "[unk]"]


modules:
  model_x_to_z: ${model.sequence_to_sequence_model.bert_bert}
  model_z_to_x: ${model.sequence_to_sequence_model.bert_bert}
  disc_x: ${model.discretizer.entmax}
  disc_z: ${model.discretizer.entmax}

model_params:
  reconstruction_loss_coeff_x: 1.0
  reconstruction_loss_coeff_z: 1.0

  tokenize_after_generation: true
  
  use_tokenizer_vocab_len: true
  disc_x_vocab_size: -1
  disc_z_vocab_size: -1
  max_x_length: 100
  max_z_length: 100