
_target_: src.datamodules.scan.SCANDatamodule
dataset_target_: src.datamodules.scan.SCANDataset
seed: 42
p_sup: ${callbacks.z_supervised_scheduler.scheduler.hp_init}
tokenize_in_dataset: True

dataset_parameters:
  seed: ${seed}
  batch_size: 128
  test_split: 'simple'
  train_ratio: 0.8
  sup_ratio: 0.1
  num_workers: 8
  overfit_batch: ${overfit_batch}
  tokenize_in_dataset: ${datamodule.tokenize_in_dataset}
  

datasets:
  seed: ${seed}
  test:
      _target_: ${datamodule.dataset_target_}
      split: "test"
  
  train:
      _target_: ${datamodule.dataset_target_}
      split: "train"
      
  val:
      _target_: ${datamodule.dataset_target_}
      split: "val"