
_target_: src.datamodules.sfst.SFSTDatamodule
dataset_target_: src.datamodules.sfst.SFSTDataset
seed: 42
tokenize_in_dataset: True
data_type_sampling_probability: [0.9, 0.05, 0.05] # [xz, x, z]

dataset_parameters:
  seed: ${seed}
  batch_size: 128
  test_split: 'simple'
  train_ratio: 0.8
  supervision_ratio: [0.05, 0.45, 0.5] # [xz, x, z]
  num_workers: 8
  overfit_batch: ${overfit_batch}
  tokenize_in_dataset: ${datamodule.tokenize_in_dataset}
  
  # SFST specific parameters
  num_object_classes: 30 
  latent_vocab_size: 10
  maximum_input_alphabet_delta: 1
  p_empty_emission: 0.3
  dataset_size: 20000
  node_size: 100
  max_length: 50
  output_alphabet_size: 10

datasets:
  seed: ${seed}
  test:
      _target_: ${datamodule.dataset_target_}
      split: "test"
  
  train:
      _target_: ${datamodule.dataset_target_}
      split: "train"
      
  val:
      _target_: ${datamodule.dataset_target_}
      split: "val"