lr: 0.001
weight_decay: 0.01
eps: 1e-08
betas: [0.9, 0.95]

disc_x:
  _target_: torch.optim.AdamW
  lr: ${float_div:${..lr},10}
  weight_decay: ${..weight_decay}
  eps: ${..eps}
  betas: ${..betas}

disc_z:
  _target_: torch.optim.AdamW
  lr: ${float_div:${..lr},10}
  weight_decay: ${..weight_decay}
  eps: ${..eps}
  betas: ${..betas}

model_x_to_z:
  _target_: torch.optim.AdamW
  lr: ${..lr}
  weight_decay: ${..weight_decay}
  eps: ${..eps}
  betas: ${..betas}

model_z_to_x:
  _target_: torch.optim.AdamW
  lr: ${..lr}
  weight_decay: ${..weight_decay}
  eps: ${..eps}
  betas: ${..betas}
