_target_: src.models.collators.simple_text_collator.HFCollator

tokenizer_x: 
    _target_: transformers.T5Tokenizer.from_pretrained
    pretrained_model_name_or_path: t5-large
tokenizer_z:
    _target_: transformers.T5Tokenizer.from_pretrained
    pretrained_model_name_or_path: t5-large

tokenizer_x_params:
  key: 'x'
  max_length: ${model.model_params.max_x_length}
  batch_size: ${datamodule.dataset_parameters.batch_size}
  max_vocab_size: ${model.model_params.max_x_vocab_size}
tokenizer_z_params:
  key: 'z'
  max_length: ${model.model_params.max_z_length}
  batch_size: ${datamodule.dataset_parameters.batch_size}
  max_vocab_size: ${model.model_params.max_z_vocab_size}

padding_side: 'right'
padding: True       
