_target_: src.models.collators.simple_text_collator.SimpleTextCollator

defaults:
  - tokenizer: simple_word_level_tokenizer

max_length: 100
padding_side: 'right'

max_X_length: ${model.collator.max_length}
max_Z_length: ${model.collator.max_length}
padding: True       
